# Generated by Django 5.0.3 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Listening', 'Listening'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reading', 'Reading'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
