# Generated by Django 5.0.3 on 2024-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_listeningmedia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningmedia',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], max_length=10),
        ),
        migrations.AlterField(
            model_name='readingmedia',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], max_length=10),
        ),
    ]
