# Generated by Django 5.0.3 on 2024-04-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_listening_time_and_more'),
        ('languages', '0002_alter_language_user_profile'),
        ('media', '0004_alter_listeningmedia_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningmedia',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AlterField(
            model_name='listeningmedia',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='readingmedia',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AlterField(
            model_name='readingmedia',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
