# Generated by Django 5.0.3 on 2024-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_listeningmedia_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmedia',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingmedia',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
