# Generated by Django 5.0.3 on 2024-03-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_current_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='listening_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='srs_time',
        ),
    ]
