# Generated by Django 5.0.3 on 2024-03-16 10:07

import ImmersionTracker.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_immersiontrackeruser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('reading_time', models.DurationField()),
                ('listening_time', models.DurationField()),
                ('srs_time', models.DurationField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='immersiontrackeruser',
            managers=[
                ('object', ImmersionTracker.accounts.models.ImmersionTrackerUserManager()),
            ],
        ),
    ]
