# Generated by Django 5.0.3 on 2024-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingentry',
            name='char_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
