# Generated by Django 5.0.3 on 2024-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion_entries', '0002_alter_readingentry_char_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningentry',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listeningentry',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='readingentry',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readingentry',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='srsentry',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='srsentry',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
    ]
