# Generated by Django 5.0.3 on 2024-03-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_alter_immersiontrackeruser_managers'),
        ('immersion_entries', '0002_listeningentry_readingentry_srsentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readingentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='srsentry',
            name='user',
        ),
        migrations.AddField(
            model_name='listeningentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='readingentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='srsentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
