# Generated by Django 5.0.3 on 2024-03-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immersion_entries', '0003_remove_listeningentry_user_remove_readingentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningentry',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='readingentry',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='srsentry',
            name='user_profile',
        ),
    ]
