# Generated by Django 5.0.3 on 2024-03-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_id_alter_profile_user'),
        ('immersion_entries', '0004_remove_listeningentry_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningentry',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='readingentry',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='srsentry',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.profile'),
        ),
    ]
