# Generated by Django 5.0.3 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion_entries', '0005_listeningentry_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingentry',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='srsentry',
            name='time_length',
            field=models.DurationField(),
        ),
        migrations.DeleteModel(
            name='ListeningEntry',
        ),
        migrations.DeleteModel(
            name='ReadingEntry',
        ),
    ]
