# Generated by Django 5.0.3 on 2024-03-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_listening_time_and_more'),
        ('immersion_entries', '0006_remove_readingentry_user_profile_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_length', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='media.listeningmedia')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_length', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('char_length', models.IntegerField(default=None)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='media.readingmedia')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
