# Generated by Django 5.0.3 on 2024-03-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immersion_entries', '0007_listeningentry_readingentry'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningentry',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='media.listeningmedia'),
        ),
        migrations.AlterField(
            model_name='readingentry',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='media.readingmedia'),
        ),
    ]
