# Generated by Django 5.0.3 on 2024-04-03 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninggoal',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='readinggoal',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='srsgoal',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='languages.language'),
        ),
    ]
